version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: slackbot-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: slackbot-mq
    ports:
      - "5672:5672"   # For Celery
      - "15672:15672" # For the Management UI

volumes:
  postgres_data: